### PR TITLE
ENH: FEI4 and TLU decoding ot orig functions

### PR DESCRIPTION
**Pull request by thirono**

### CODE REVIEW

**Comment by laborleben** [comment]
is this a cleanup?

**Comment by DavidLP** [comment]
Thank you for the pull request. But we do not want to have FEI4 interpretation in this package. For this we have the pybar_FEI4_interpreter that is more mature and has more features and tests. Also it would be nice if you do not change your old function that is not used anymore, but take the translated code I commited.

**Comment by themperek** [comment]
Actually maybe usefull to keep this for reference in separate inactive branch but remove here.

**Comment by DavidLP** [comment]
For sure. It very usefull for cross checking. I event use the old interpretation function in the unit tests to test against ;-)

**Comment by thirono** [comment]
the change was applied to development branch

**Pull request closed without merging**
