### PR TITLE
Limit amount of buffered data and specify planes to be analyzed

### PR DESCRIPTION
**Pull request by YannickDieter**
1. Limits size of buffer of telescope data which is needed in case time between triggers is too long. Data with timestamps older than actual timestamp minus `MAX_BUFFER_TIME_SLIP` will be dropped.
2. Select telescope planes by header ID that will be analyzed. Now any number of planes are supported. Any header IDs are supported.
3. Updated plotting
4. Updated/fixed unittests and example
5. Fixed buffer underrun bug

### CODE REVIEW

**Comment by YannickDieter** [comment]
@laborleben These are the changes as discussed yesterday. Just merge if you are fine with that.

**Comment by laborleben** [comment]
Can you test, please?

**Comment by laborleben** [comment]
@YannickDieter **active_m26_planes** -> **analyze_m26_header_ids**

**Comment by laborleben** [comment]
All checks are passing. There is still a bug in `test_interpreter.py:create_raw_data()`.

Data file are identical before and after changes. Note that the column `plane` now contains the header ID.

**Pull request merged**
